### ISSUE TITLE
MLEE bug

### ISSUE THREAD

**Issue by sunnnymskang** [bigscience-workshop/biomedical#185]
if __name__ == "__main__":
    from datasets import load_dataset
    # ds = load_dataset(__file__)
    ds = load_dataset(__file__, name = "mlee_bigbio_kb")
    print(ds)

produces 

Traceback (most recent call last):
  File "/Users/skang/repo/bigscience/biomedical/examples/mlee.py", line 346, in <module>
    ds = load_dataset(__file__)
  File "/Users/skang/repo/bigscience/biomedical/venv/lib/python3.8/site-packages/datasets/load.py", line 1694, in load_dataset
    builder_instance.download_and_prepare(
  File "/Users/skang/repo/bigscience/biomedical/venv/lib/python3.8/site-packages/datasets/builder.py", line 595, in download_and_prepare
    self._download_and_prepare(
  File "/Users/skang/repo/bigscience/biomedical/venv/lib/python3.8/site-packages/datasets/builder.py", line 684, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/Users/skang/repo/bigscience/biomedical/venv/lib/python3.8/site-packages/datasets/builder.py", line 1076, in _prepare_split
    for key, record in utils.tqdm(
  File "/Users/skang/repo/bigscience/biomedical/venv/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/Users/skang/.cache/huggingface/modules/datasets_modules/datasets/mlee/7213f66b461cc6aca737b76e18ef57a1bd65247ad8efc15609d4e47e01bd2b75/mlee.py", line 328, in _generate_examples
    example = utils.parse_brat_file(txt_file)
  File "/Users/skang/repo/bigscience/biomedical/examples/utils.py", line 91, in parse_brat_file
    example["document_id"] = txt_file.name.removesuffix(".txt")
AttributeError: 'str' object has no attribute 'removesuffix'

**Comment by sunnnymskang** [comment]
@leonweber - Can you take a look at this?

**Comment by leonweber** [comment]
@sunnnymskang Should be resolved now
